# Generated by Django 5.1.4 on 2025-01-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=100)),
                ('paralegal', models.CharField(max_length=100)),
                ('office', models.CharField(choices=[('Hartford', 'Hartford'), ('Waterbury', 'Waterbury')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
