# Generated by Django 5.1.4 on 2025-02-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='folder_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
