# Generated by Django 5.1.4 on 2025-01-29 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='attorney',
        ),
        migrations.RemoveField(
            model_name='client',
            name='paralegal',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='requester',
        ),
        migrations.AddField(
            model_name='client',
            name='attorney',
            field=models.ManyToManyField(related_name='client_attorney', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='paralegal',
            field=models.ManyToManyField(related_name='client_paralegal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='requester',
            field=models.ManyToManyField(related_name='medical_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
