# Generated by Django 5.1.4 on 2025-02-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_folder_id_client_expense_folder_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sharepoint_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
