# Generated by Django 5.1.4 on 2025-02-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='approval_file_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='expense_file_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='invoice_file_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='package_file_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='receipt_file_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='record_file_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
