# Generated by Django 5.1.4 on 2025-02-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_medicalrecord_approval_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='last_approval_message_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='notify_attorney',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='notify_requester',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='reply_to',
            field=models.BooleanField(default=False),
        ),
    ]
