# Generated by Django 5.1.4 on 2025-02-20 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_medicalrecord_last_approval_message_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='requester',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='requester',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Requester'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
