# Generated by Django 5.1.4 on 2025-02-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_remove_medicalrecord_requester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='skip_request',
            field=models.BooleanField(default=False),
        ),
    ]
