# Generated by Django 5.2 on 2025-05-03 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('is_cd', models.BooleanField(default=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('skip_request', models.BooleanField(default=False)),
                ('notify_requester', models.BooleanField(default=True)),
                ('notify_attorney', models.BooleanField(default=False)),
                ('reply_to', models.BooleanField(default=False)),
                ('last_approval_message_id', models.CharField(blank=True, max_length=500, null=True)),
                ('temp_folder_id', models.CharField(blank=True, max_length=500, null=True)),
                ('invoice_path', models.CharField(blank=True, max_length=500, null=True)),
                ('approval_path', models.CharField(blank=True, max_length=500, null=True)),
                ('receipt_path', models.CharField(blank=True, max_length=500, null=True)),
                ('expense_path', models.CharField(blank=True, max_length=500, null=True)),
                ('record_path', models.CharField(blank=True, max_length=500, null=True)),
                ('package_path', models.CharField(blank=True, max_length=500, null=True)),
                ('invoice_file_id', models.CharField(blank=True, max_length=500, null=True)),
                ('approval_file_id', models.CharField(blank=True, max_length=500, null=True)),
                ('receipt_file_id', models.CharField(blank=True, max_length=500, null=True)),
                ('expense_file_id', models.CharField(blank=True, max_length=500, null=True)),
                ('record_file_id', models.CharField(blank=True, max_length=500, null=True)),
                ('package_file_id', models.CharField(blank=True, max_length=500, null=True)),
                ('is_denied', models.BooleanField(default=False)),
                ('skip_download', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('NEW_ENTRY', 'new_entry'), ('PENDING_APPROVAL', 'pending_approval'), ('DENIED', 'denied'), ('PENDING_PAYMENT', 'pending_payment'), ('PENDING_RECORDS', 'pending_records'), ('COMPLETED', 'completed')], default='NEW_ENTRY', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='core.client')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to='core.provider')),
                ('requester', models.ForeignKey(limit_choices_to={'groups__name': 'Requester'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Record',
                'verbose_name_plural': 'Medical Records',
            },
        ),
    ]
